<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Validación y regularización – MATE-2105: Módulo 1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./capitulo04_regresion_logistica.html" rel="next">
<link href="./capitulo02_descenso_gradiente.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-bf8030b5a8b8f2de5bceddfb8bf38a1d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating textbook-chapter quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./capitulo03_regularizacion_validacion.html"><span class="chapter-title">Validación y regularización</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">MATE-2105: Módulo 1</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Módulo 1: Regresión, optimización, regularización y clasificación</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./capitulo01_regresion_lineal.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Regresión lineal y mínimos cuadrados</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./capitulo02_descenso_gradiente.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Descenso del gradiente</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./capitulo03_regularizacion_validacion.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Validación y regularización</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./capitulo04_regresion_logistica.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Regresión logística</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./capitulo05_ejercicios_integradores.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Problemas integradores de regresión y clasificación</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./apendice_formulario_respuestas.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Apéndice Módulo 1: formulario y respuestas seleccionadas</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./laboratorios/lab01_regresion_gradiente.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lab 1: Regresión lineal y descenso del gradiente</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./laboratorios/lab02_regularizacion_clasificacion.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lab 2: Regularización, validación y clasificación</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./laboratorios/parcial01_autograded.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Parcial 1 autograded</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./recursos/guia_parcial1.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Guía de preparación Parcial 1</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./recursos/guia_proyecto_modulo01.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Proyecto durante el Módulo 1</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#capacidad-y-comportamiento-fuera-de-muestra" id="toc-capacidad-y-comportamiento-fuera-de-muestra" class="nav-link active" data-scroll-target="#capacidad-y-comportamiento-fuera-de-muestra">Capacidad y comportamiento fuera de muestra</a></li>
  <li><a href="#tres-funciones-para-tres-conjuntos-de-datos" id="toc-tres-funciones-para-tres-conjuntos-de-datos" class="nav-link" data-scroll-target="#tres-funciones-para-tres-conjuntos-de-datos">Tres funciones para tres conjuntos de datos</a></li>
  <li><a href="#transformaciones-y-filtración-de-información" id="toc-transformaciones-y-filtración-de-información" class="nav-link" data-scroll-target="#transformaciones-y-filtración-de-información">Transformaciones y filtración de información</a></li>
  <li><a href="#ridge-encoger-direcciones-inestables" id="toc-ridge-encoger-direcciones-inestables" class="nav-link" data-scroll-target="#ridge-encoger-direcciones-inestables">Ridge: encoger direcciones inestables</a>
  <ul class="collapse">
  <li><a href="#qué-ocurre-en-las-direcciones-singulares" id="toc-qué-ocurre-en-las-direcciones-singulares" class="nav-link" data-scroll-target="#qué-ocurre-en-las-direcciones-singulares">Qué ocurre en las direcciones singulares</a></li>
  </ul></li>
  <li><a href="#lasso-una-penalización-con-esquina" id="toc-lasso-una-penalización-con-esquina" class="nav-link" data-scroll-target="#lasso-una-penalización-con-esquina">Lasso: una penalización con esquina</a></li>
  <li><a href="#seleccionar-sin-consultar-prueba" id="toc-seleccionar-sin-consultar-prueba" class="nav-link" data-scroll-target="#seleccionar-sin-consultar-prueba">Seleccionar sin consultar prueba</a></li>
  <li><a href="#regreso-a-las-subzonas-de-bogotá" id="toc-regreso-a-las-subzonas-de-bogotá" class="nav-link" data-scroll-target="#regreso-a-las-subzonas-de-bogotá">Regreso a las subzonas de Bogotá</a></li>
  <li><a href="#síntesis" id="toc-síntesis" class="nav-link" data-scroll-target="#síntesis">Síntesis</a></li>
  <li><a href="#problemas" id="toc-problemas" class="nav-link" data-scroll-target="#problemas">Problemas</a>
  <ul class="collapse">
  <li><a href="#complejidad-que-mejora-el-objetivo-equivocado" id="toc-complejidad-que-mejora-el-objetivo-equivocado" class="nav-link" data-scroll-target="#complejidad-que-mejora-el-objetivo-equivocado">1. Complejidad que mejora el objetivo equivocado</a></li>
  <li><a href="#una-tubería-con-y-sin-filtración" id="toc-una-tubería-con-y-sin-filtración" class="nav-link" data-scroll-target="#una-tubería-con-y-sin-filtración">2. Una tubería con y sin filtración</a></li>
  <li><a href="#ridge-en-una-dirección-casi-redundante" id="toc-ridge-en-una-dirección-casi-redundante" class="nav-link" data-scroll-target="#ridge-en-una-dirección-casi-redundante">3. Ridge en una dirección casi redundante</a></li>
  <li><a href="#lasso-y-columnas-correlacionadas" id="toc-lasso-y-columnas-correlacionadas" class="nav-link" data-scroll-target="#lasso-y-columnas-correlacionadas">4. Lasso y columnas correlacionadas</a></li>
  <li><a href="#validación-con-32-subzonas" id="toc-validación-con-32-subzonas" class="nav-link" data-scroll-target="#validación-con-32-subzonas">5. Validación con 32 subzonas</a></li>
  </ul></li>
  <li><a href="#respuestas-seleccionadas" id="toc-respuestas-seleccionadas" class="nav-link" data-scroll-target="#respuestas-seleccionadas">Respuestas seleccionadas</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Validación y regularización</span></h1>
<p class="subtitle lead">Cómo escoger complejidad sin confundir ajuste con generalización</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>La variable <code>x1</code> del conjunto sintético produjo una recta con MSE cercano a 2. Podemos construir una familia mucho más flexible sin añadir nuevas mediciones:</p>
<p><span class="math display">\[
\boldsymbol\phi_d(x)
=\begin{bmatrix}x&amp;x^2&amp;\cdots&amp;x^d\end{bmatrix}^{\!\top}.
\]</span></p>
<p>Dividamos las 160 filas, con semillas fijadas, en 80 para entrenamiento, 40 para validación y 40 para prueba. Ajustar polinomios por mínimos cuadrados produce:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">grado</th>
<th style="text-align: right;">MSE entrenamiento</th>
<th style="text-align: right;">MSE validación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.993</td>
<td style="text-align: right;">2.223</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">1.965</td>
<td style="text-align: right;">2.172</td>
</tr>
<tr class="odd">
<td style="text-align: right;">8</td>
<td style="text-align: right;">1.749</td>
<td style="text-align: right;">2.379</td>
</tr>
<tr class="even">
<td style="text-align: right;">15</td>
<td style="text-align: right;">1.542</td>
<td style="text-align: right;">3.254</td>
</tr>
</tbody>
</table>
<p>El grado 15 resuelve mejor el problema que se le pidió durante el ajuste: tiene el menor error de entrenamiento. También produce el peor resultado en las 40 observaciones que no utilizó. La optimización no falló. El criterio de selección era incompleto.</p>
<section id="capacidad-y-comportamiento-fuera-de-muestra" class="level2">
<h2 class="anchored" data-anchor-id="capacidad-y-comportamiento-fuera-de-muestra">Capacidad y comportamiento fuera de muestra</h2>
<p>Una regresión polinomial sigue siendo lineal en sus parámetros:</p>
<p><span class="math display">\[
f_{\boldsymbol\theta}(x)
=\theta_0+\theta_1x+\cdots+\theta_dx^d.
\]</span></p>
<p>Al aumentar <span class="math inline">\(d\)</span>, la familia contiene a las anteriores y el mínimo de la pérdida de entrenamiento no puede aumentar, salvo diferencias numéricas. Esa propiedad no se extiende al riesgo poblacional. Los parámetros de orden alto pueden adaptarse a fluctuaciones particulares de la muestra.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> polynomial_features_1d(x, degree):</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> np.asarray(x, dtype<span class="op">=</span><span class="bu">float</span>).reshape(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    columns <span class="op">=</span> [np.ones((x.shape[<span class="dv">0</span>], <span class="dv">1</span>))]</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    columns.extend(x <span class="op">**</span> power <span class="cf">for</span> power <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, degree <span class="op">+</span> <span class="dv">1</span>))</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.hstack(columns)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>La transformación <span class="math inline">\(x\mapsto(x,x^2,\ldots,x^d)\)</span> es determinista por fila. No consulta otras observaciones. El grado, en cambio, define una familia y debe elegirse sin utilizar la evaluación final.</p>
<p>Si <span class="math inline">\(D_n\)</span> representa la muestra de ajuste y <span class="math inline">\(\widehat f_{D_n}\)</span> la función obtenida, repetir el muestreo produce otra función. Para pérdida cuadrática y una entrada fija <span class="math inline">\(\boldsymbol x\)</span>, bajo condiciones usuales,</p>
<p><span class="math display">\[
\begin{aligned}
\mathbb E_{D_n,Y\mid\boldsymbol x}
[(Y-\widehat f_{D_n}(\boldsymbol x))^2]
={}&amp;\operatorname{Var}(Y\mid\boldsymbol X=\boldsymbol x)\\
&amp;+\operatorname{Bias}(\boldsymbol x)^2\\
&amp;+\operatorname{Var}_{D_n}
(\widehat f_{D_n}(\boldsymbol x)),
\end{aligned}
\]</span></p>
<p>donde</p>
<p><span class="math display">\[
\operatorname{Bias}(\boldsymbol x)
=\mathbb E_{D_n}[\widehat f_{D_n}(\boldsymbol x)]
-\mathbb E[Y\mid\boldsymbol X=\boldsymbol x].
\]</span></p>
<p>Una familia demasiado rígida puede tener sesgo alto. Una familia muy flexible puede responder con intensidad a las particularidades de <span class="math inline">\(D_n\)</span>. La regularización modifica este balance; la validación proporciona datos para compararlo.</p>
<div id="fig-cap03-curvas-aprendizaje" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Tres paneles de curvas de aprendizaje. Sobreajuste muestra una brecha persistente, subajuste muestra errores altos y el caso estable muestra convergencia de entrenamiento y validación.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cap03-curvas-aprendizaje-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figuras/curvas-aprendizaje.svg" class="img-fluid figure-img" style="width:100.0%" alt="Tres paneles de curvas de aprendizaje. Sobreajuste muestra una brecha persistente, subajuste muestra errores altos y el caso estable muestra convergencia de entrenamiento y validación.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cap03-curvas-aprendizaje-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.1: Curvas de aprendizaje: el sobreajuste mantiene una brecha entre entrenamiento y validación, el subajuste mantiene ambos errores altos y un caso estable reduce la brecha al aumentar los datos.
</figcaption>
</figure>
</div>
<p>Una curva de aprendizaje es un diagnóstico, no una prueba automática de una causa. Una brecha puede sugerir sensibilidad a la muestra; errores altos en ambos conjuntos pueden sugerir una familia inadecuada, una representación pobre o una optimización incompleta.</p>
</section>
<section id="tres-funciones-para-tres-conjuntos-de-datos" class="level2">
<h2 class="anchored" data-anchor-id="tres-funciones-para-tres-conjuntos-de-datos">Tres funciones para tres conjuntos de datos</h2>
<p>Entrenamiento, validación y prueba no son tres nombres para muestras intercambiables.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>conjunto</th>
<th>decisiones que permite</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>entrenamiento</td>
<td>ajustar parámetros y transformaciones aprendidas</td>
</tr>
<tr class="even">
<td>validación</td>
<td>escoger grado, penalización y otras configuraciones</td>
</tr>
<tr class="odd">
<td>prueba</td>
<td>evaluar una vez el procedimiento ya fijado</td>
</tr>
</tbody>
</table>
<div class="proposicion">
<p><strong>Validación de una regla fijada.</strong> Sea <span class="math inline">\(f\)</span> una función que no utilizó el conjunto de validación. Si <span class="math inline">\(Z_1^{\mathrm{val}},\ldots,Z_v^{\mathrm{val}}\)</span> son iid de la población <span class="math inline">\(P\)</span>, entonces</p>
<p><span class="math display">\[
\mathbb E[\widehat R_{\mathrm{val}}(f)\mid f]
=R_P(f),
\]</span></p>
<p>si la pérdida es integrable.</p>
</div>
<div class="demostracion">
<p>Condicionado en <span class="math inline">\(f\)</span>, cada pérdida <span class="math inline">\(\ell(f;Z_i^{\mathrm{val}})\)</span> tiene esperanza <span class="math inline">\(R_P(f)\)</span>. La linealidad de la esperanza aplicada al promedio da la igualdad.</p>
</div>
<p>Después de comparar muchos modelos y escoger el menor valor observado en esa misma validación, la función elegida ya depende de los datos de validación. El mínimo incorpora optimismo por selección. El conjunto de prueba se reserva para el procedimiento completo: transformaciones, familia, hiperparámetros, umbral y regla de entrenamiento.</p>
<p>Cuando hay pocas observaciones, la validación cruzada reutiliza de manera estructurada distintas partes de los datos para comparar configuraciones. No elimina la incertidumbre ni autoriza usar prueba durante el diseño. El capítulo de estrategia estudiará sus estimaciones con más detalle.</p>
</section>
<section id="transformaciones-y-filtración-de-información" class="level2">
<h2 class="anchored" data-anchor-id="transformaciones-y-filtración-de-información">Transformaciones y filtración de información</h2>
<p>Una transformación puede ser fija o aprender cantidades de los datos.</p>
<ul>
<li><span class="math inline">\(x\mapsto x^2\)</span> se aplica a una fila sin estimar nada de las demás.</li>
<li>La estandarización necesita medias y desviaciones.</li>
<li>La imputación necesita reglas o valores de reemplazo.</li>
<li>Una codificación puede aprender qué categorías existen.</li>
<li>La selección de variables utiliza una medida calculada con respuestas.</li>
</ul>
<p>Las cantidades aprendidas se ajustan solo con entrenamiento y se aplican sin reestimarlas a validación y prueba. De lo contrario, información reservada cambia la representación usada para entrenar.</p>
<div class="diagnostico">
<p><strong>Dos filtraciones diferentes.</strong> Calcular la media de estandarización con toda la tabla filtra información entre observaciones. Incluir una variable registrada después del resultado filtra información temporal. Una tubería de software ayuda con la primera; la segunda exige comprender cómo se produce cada columna.</p>
</div>
<p>Una implementación con <code>scikit-learn</code> mantiene juntos transformación y ajuste:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> Ridge</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.pipeline <span class="im">import</span> make_pipeline</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> PolynomialFeatures, StandardScaler</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> make_pipeline(</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    PolynomialFeatures(degree<span class="op">=</span><span class="dv">3</span>, include_bias<span class="op">=</span><span class="va">False</span>),</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    StandardScaler(),</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    Ridge(alpha<span class="op">=</span><span class="fl">1.0</span>, fit_intercept<span class="op">=</span><span class="va">True</span>),</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>model.fit(X_train, y_train)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>validation_prediction <span class="op">=</span> model.predict(X_validation)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>El método <code>fit</code> de la tubería aprende polinomio, escalas y regresión únicamente a partir de entrenamiento. <code>predict</code> reutiliza esos objetos.</p>
</section>
<section id="ridge-encoger-direcciones-inestables" class="level2">
<h2 class="anchored" data-anchor-id="ridge-encoger-direcciones-inestables">Ridge: encoger direcciones inestables</h2>
<p>Ridge añade una penalización cuadrática a la pérdida. Con el intercepto en la primera columna de <span class="math inline">\(\mathbf X\)</span>, definimos</p>
<p><span class="math display">\[
\mathbf D=\operatorname{diag}(0,1,\ldots,1)
\]</span></p>
<p>y</p>
<p><span class="math display">\[
J_{\mathrm{Ridge}}(\boldsymbol\theta)
=\frac1{2n}
\lVert\mathbf X\boldsymbol\theta-\mathbf y\rVert_2^2
+\frac\lambda2\boldsymbol\theta^\top
\mathbf D\boldsymbol\theta.
\]</span></p>
<p>El cero inicial evita penalizar el intercepto. El gradiente es</p>
<p><span class="math display">\[
\nabla J_{\mathrm{Ridge}}(\boldsymbol\theta)
=\frac1n\mathbf X^\top
(\mathbf X\boldsymbol\theta-\mathbf y)
+\lambda\mathbf D\boldsymbol\theta.
\]</span></p>
<p>Igualarlo a cero produce</p>
<p><span class="math display">\[
(\mathbf X^\top\mathbf X+n\lambda\mathbf D)
\widehat{\boldsymbol\theta}_{\lambda}
=\mathbf X^\top\mathbf y.
\]</span></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> ridge_closed_form(X, y, lam):</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    n, p <span class="op">=</span> X.shape</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    penalty <span class="op">=</span> np.eye(p)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    penalty[<span class="dv">0</span>, <span class="dv">0</span>] <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    system <span class="op">=</span> X.T <span class="op">@</span> X <span class="op">+</span> n <span class="op">*</span> lam <span class="op">*</span> penalty</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.linalg.solve(system, X.T <span class="op">@</span> y)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Esta función implementa la convención del libro. <code>sklearn.linear_model.Ridge</code> minimiza</p>
<p><span class="math display">\[
\lVert\mathbf y-\mathbf X\mathbf w\rVert_2^2
+\alpha\lVert\mathbf w\rVert_2^2.
\]</span></p>
<p>Por tanto, para el mismo diseño y sin penalizar el intercepto, <span class="math inline">\(\alpha=n\lambda\)</span>. Usar el mismo número para <code>alpha</code> y <span class="math inline">\(\lambda\)</span> sin considerar la normalización no reproduce el mismo problema.</p>
<section id="qué-ocurre-en-las-direcciones-singulares" class="level3">
<h3 class="anchored" data-anchor-id="qué-ocurre-en-las-direcciones-singulares">Qué ocurre en las direcciones singulares</h3>
<p>Para estudiar los coeficientes no intercepto, supongamos que las características están centradas y escribamos <span class="math inline">\(\mathbf X=\mathbf U\boldsymbol\Sigma\mathbf V^\top\)</span>. Ridge actúa como</p>
<p><span class="math display">\[
\widehat{\boldsymbol\theta}_{\lambda}
=\mathbf V
(\boldsymbol\Sigma^\top\boldsymbol\Sigma+n\lambda\mathbf I)^{-1}
\boldsymbol\Sigma^\top\mathbf U^\top\mathbf y.
\]</span></p>
<p>En la dirección derecha <span class="math inline">\(\boldsymbol v_j\)</span>, el factor</p>
<p><span class="math display">\[
\frac{\sigma_j}{\sigma_j^2+n\lambda}
\]</span></p>
<p>reemplaza el factor <span class="math inline">\(1/\sigma_j\)</span> de mínimos cuadrados. Las direcciones con <span class="math inline">\(\sigma_j\)</span> pequeño, que son las más sensibles, se encogen con mayor intensidad. La estabilidad se obtiene a cambio de sesgo.</p>
<div id="fig-cap03-regularizacion-ridge-lasso" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Tres paneles comparan barras de coeficientes. Mínimos cuadrados tiene barras grandes, Ridge muestra barras más pequeñas y Lasso muestra algunas barras en cero.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cap03-regularizacion-ridge-lasso-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figuras/regularizacion-ridge-lasso.svg" class="img-fluid figure-img" style="width:100.0%" alt="Tres paneles comparan barras de coeficientes. Mínimos cuadrados tiene barras grandes, Ridge muestra barras más pequeñas y Lasso muestra algunas barras en cero.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cap03-regularizacion-ridge-lasso-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.2: Regularización: mínimos cuadrados puede producir coeficientes grandes, Ridge reduce magnitudes y Lasso puede llevar coeficientes exactamente a cero.
</figcaption>
</figure>
</div>
<p>Un <span class="math inline">\(\lambda\)</span> positivo no garantiza menor riesgo. Si es demasiado grande, las predicciones se acercan a una regla casi constante y pueden perder estructura real. Su valor se selecciona con validación.</p>
</section>
</section>
<section id="lasso-una-penalización-con-esquina" class="level2">
<h2 class="anchored" data-anchor-id="lasso-una-penalización-con-esquina">Lasso: una penalización con esquina</h2>
<p>Lasso utiliza</p>
<p><span class="math display">\[
J_{\mathrm{Lasso}}(\boldsymbol\theta)
=\frac1{2n}
\lVert\mathbf X\boldsymbol\theta-\mathbf y\rVert_2^2
+\lambda\sum_{j=1}^{p-1}|\theta_j|.
\]</span></p>
<p>De nuevo, el intercepto no se penaliza. La función <span class="math inline">\(|t|\)</span> no es diferenciable en cero; su subdiferencial es</p>
<p><span class="math display">\[
\partial|t|=
\begin{cases}
\{1\}, &amp; t&gt;0,\\
[-1,1], &amp; t=0,\\
\{-1\}, &amp; t&lt;0.
\end{cases}
\]</span></p>
<p>Sea <span class="math inline">\(\mathbf x_j\)</span> la columna <span class="math inline">\(j\)</span> del diseño. Una solución satisface</p>
<p><span class="math display">\[
0\in
\frac1n\mathbf x_j^\top
(\mathbf X\widehat{\boldsymbol\theta}-\mathbf y)
+\lambda\,\partial|\widehat\theta_j|.
\]</span></p>
<p>La coordenada puede quedar exactamente en cero cuando</p>
<p><span class="math display">\[
\left|
\frac1n\mathbf x_j^\top
(\mathbf y-\mathbf X\widehat{\boldsymbol\theta})
\right|\leq\lambda.
\]</span></p>
<p>La esquina de la penalización permite que un intervalo de gradientes residuales sea compatible con cero. El operador de umbral suave</p>
<p><span class="math display">\[
S(a,\lambda)
=\operatorname{sign}(a)\max\{|a|-\lambda,0\}
\]</span></p>
<p>aparece al resolver una coordenada a la vez. Si <span class="math inline">\(\mathbf r_{-j}=\mathbf y-\sum_{k\ne j}\mathbf x_k\theta_k\)</span>, la actualización es</p>
<p><span class="math display">\[
\theta_j\leftarrow
\frac{S(\mathbf x_j^\top\mathbf r_{-j}/n,\lambda)}
{\lVert\mathbf x_j\rVert_2^2/n}.
\]</span></p>
<p>Con variables muy correlacionadas, Lasso puede escoger una y dejar otra en cero de manera sensible a la muestra. Un cero describe la solución penalizada para ese diseño y ese <span class="math inline">\(\lambda\)</span>; no demuestra irrelevancia causal ni ausencia de asociación poblacional.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>aspecto</th>
<th>Ridge</th>
<th>Lasso</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>penalización</td>
<td>suma de cuadrados</td>
<td>suma de valores absolutos</td>
</tr>
<tr class="even">
<td>efecto habitual</td>
<td>encogimiento continuo</td>
<td>algunos ceros exactos</td>
</tr>
<tr class="odd">
<td>columnas correlacionadas</td>
<td>tiende a repartir peso</td>
<td>puede escoger una</td>
</tr>
<tr class="even">
<td>cálculo</td>
<td>sistema lineal</td>
<td>algoritmo iterativo, por ejemplo coordenadas</td>
</tr>
<tr class="odd">
<td>propósito frecuente</td>
<td>estabilidad predictiva</td>
<td>esparsidad y predicción</td>
</tr>
</tbody>
</table>
<p>Como ambas penalizaciones actúan sobre coeficientes, las características deben tener escalas comparables. El intercepto se mantiene separado de la estandarización y de la penalización.</p>
</section>
<section id="seleccionar-sin-consultar-prueba" class="level2">
<h2 class="anchored" data-anchor-id="seleccionar-sin-consultar-prueba">Seleccionar sin consultar prueba</h2>
<p>Volvamos al polinomio de grado 15. Después de ajustar <code>PolynomialFeatures</code> y <code>StandardScaler</code> con entrenamiento, obtenemos:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;"><code>alpha</code> de <code>Ridge</code></th>
<th style="text-align: right;">MSE entrenamiento</th>
<th style="text-align: right;">MSE validación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.542</td>
<td style="text-align: right;">3.254</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.0001</td>
<td style="text-align: right;">1.655</td>
<td style="text-align: right;">2.552</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">1.756</td>
<td style="text-align: right;">2.317</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">1.790</td>
<td style="text-align: right;">2.274</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.848</td>
<td style="text-align: right;">2.199</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">1.953</td>
<td style="text-align: right;">2.326</td>
</tr>
<tr class="odd">
<td style="text-align: right;">100</td>
<td style="text-align: right;">2.647</td>
<td style="text-align: right;">3.396</td>
</tr>
</tbody>
</table>
<p>Ridge reduce la brecha del polinomio de grado 15. Sin embargo, el polinomio de grado 3 obtiene MSE de validación 2.172 y resulta ligeramente mejor entre las configuraciones comparadas. Se fija entonces el procedimiento de grado 3 y se consulta prueba por primera vez: su MSE es 2.103. La regla de referencia, cuya media se calculó solo con entrenamiento, obtiene 5.533.</p>
<p>Esta evaluación no prueba que el grado 3 sea óptimo para toda muestra futura. Sí documenta una comparación reproducible en la que la prueba no participó en la selección.</p>
</section>
<section id="regreso-a-las-subzonas-de-bogotá" class="level2">
<h2 class="anchored" data-anchor-id="regreso-a-las-subzonas-de-bogotá">Regreso a las subzonas de Bogotá</h2>
<p>En el caso de Bogotá solo hay 32 filas. Una partición de 24 subzonas para ajuste y 8 para evaluación produce una métrica muy sensible a cuáles subzonas quedaron en cada grupo.</p>
<div id="fig-cap03-vivienda-bogota-variacion-particiones" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Gráfico de líneas del MAE para ocho semillas. La regla de referencia y el modelo lineal cambian de manera visible entre particiones.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cap03-vivienda-bogota-variacion-particiones-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figuras/vivienda-bogota-variacion-particiones.svg" class="img-fluid figure-img" style="width:90.0%" alt="Gráfico de líneas del MAE para ocho semillas. La regla de referencia y el modelo lineal cambian de manera visible entre particiones.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cap03-vivienda-bogota-variacion-particiones-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.3: El MAE cambia entre particiones de las 32 subzonas. La semilla registra una fuente de variación; no debe escogerse por producir el menor error.
</figcaption>
</figure>
</div>
<p>Escoger la semilla con menor MAE sería otra forma de usar la evaluación para diseñar el resultado. Una comparación responsable fija el mecanismo de partición antes de ver las métricas y muestra su variación. Con tan pocas unidades, la validación cruzada puede aprovechar mejor las filas, pero las unidades siguen siendo agregadas y no están documentadas como una muestra aleatoria de una población más amplia.</p>
<p>Ridge puede estabilizar los coeficientes correlacionados de área, alcobas, baños y parqueaderos. Esa estabilidad resuelve una dificultad del ajuste; no recupera la variación dentro de cada subzona ni la unidad ausente de <code>precio_reportado</code>.</p>
</section>
<section id="síntesis" class="level2">
<h2 class="anchored" data-anchor-id="síntesis">Síntesis</h2>
<p>Una familia más flexible siempre puede mejorar o conservar el mejor ajuste de entrenamiento. El ejemplo polinomial muestra por qué ese orden no determina el comportamiento fuera de muestra. Entrenamiento ajusta parámetros y transformaciones; validación compara configuraciones; prueba evalúa el procedimiento fijado.</p>
<p>Ridge añade una penalización cuadrática que encoge especialmente las direcciones mal determinadas. Lasso utiliza valores absolutos y puede producir ceros por su condición de subgradiente. En ambos casos, el intercepto no se penaliza y las características se estandarizan con estadísticas aprendidas solo en entrenamiento.</p>
<p>Regularizar, validar y evitar filtración son partes del mismo procedimiento. Una buena métrica de prueba no borra, sin embargo, las restricciones de unidad, muestreo y medición establecidas antes del ajuste.</p>
</section>
<section id="problemas" class="level2">
<h2 class="anchored" data-anchor-id="problemas">Problemas</h2>
<section id="complejidad-que-mejora-el-objetivo-equivocado" class="level3">
<h3 class="anchored" data-anchor-id="complejidad-que-mejora-el-objetivo-equivocado">1. Complejidad que mejora el objetivo equivocado</h3>
<p>Use <code>x1</code> y <code>target</code> de <code>regresion_lineal_sintetica.csv</code> con las particiones descritas al inicio.</p>
<ol type="1">
<li>Reproduzca la tabla para grados 1, 3, 8 y 15.</li>
<li>Grafique cada polinomio dentro y fuera del rango central de entrenamiento.</li>
<li>Compare normas de coeficientes y números de condición.</li>
<li>Explique por qué el error de entrenamiento debe ser no creciente si los espacios polinomiales están anidados y la solución es exacta.</li>
<li>Seleccione un grado con validación y consulte prueba una sola vez.</li>
</ol>
</section>
<section id="una-tubería-con-y-sin-filtración" class="level3">
<h3 class="anchored" data-anchor-id="una-tubería-con-y-sin-filtración">2. Una tubería con y sin filtración</h3>
<p>Construya una variable con faltantes y una categoría poco frecuente.</p>
<ol type="1">
<li>Divida los datos antes de imputar, codificar o estandarizar.</li>
<li>Implemente una tubería que aprenda todas esas transformaciones con entrenamiento.</li>
<li>Implemente deliberadamente una versión que las aprenda con toda la tabla.</li>
<li>Compare los objetos aprendidos, no solo la métrica final.</li>
<li>Identifique cuál información reservada ingresó en cada transformación y por qué una diferencia pequeña en la métrica no vuelve correcto el procedimiento.</li>
</ol>
</section>
<section id="ridge-en-una-dirección-casi-redundante" class="level3">
<h3 class="anchored" data-anchor-id="ridge-en-una-dirección-casi-redundante">3. Ridge en una dirección casi redundante</h3>
<p>Use el conjunto sintético y añada <code>x4 = x1 + 0.001*ruido</code>, con semilla fija.</p>
<ol type="1">
<li>Estandarice las características usando solo entrenamiento.</li>
<li>Compare valores singulares y coeficientes de OLS con los de Ridge para una rejilla de <span class="math inline">\(\lambda\)</span>.</li>
<li>Verifique la fórmula <span class="math inline">\(\sigma_j/(\sigma_j^2+n\lambda)\)</span> en las direcciones singulares.</li>
<li>Compare pérdida de entrenamiento, validación y norma de coeficientes.</li>
<li>Explique qué estabilidad se ganó y qué sesgo se introdujo.</li>
</ol>
</section>
<section id="lasso-y-columnas-correlacionadas" class="level3">
<h3 class="anchored" data-anchor-id="lasso-y-columnas-correlacionadas">4. Lasso y columnas correlacionadas</h3>
<p>Genere dos predictores altamente correlacionados y una respuesta que dependa de ambos.</p>
<ol type="1">
<li>Ajuste Lasso para una secuencia de penalizaciones.</li>
<li>Verifique la condición de subgradiente en una coordenada igual a cero.</li>
<li>Repita el experimento con diez semillas y registre cuál variable queda activa.</li>
<li>Compare predicciones y selección de columnas entre repeticiones.</li>
<li>Redacte una conclusión que distinga esparsidad computada, estabilidad y relevancia sustantiva.</li>
</ol>
</section>
<section id="validación-con-32-subzonas" class="level3">
<h3 class="anchored" data-anchor-id="validación-con-32-subzonas">5. Validación con 32 subzonas</h3>
<p>Use el caso de Bogotá.</p>
<ol type="1">
<li>Defina una tubería con estandarización y Ridge.</li>
<li>Compare una rejilla de penalizaciones mediante particiones fijadas o validación cruzada.</li>
<li>Incluya la regla de referencia en cada división y conserve resultados por subzona.</li>
<li>Muestre la distribución de métricas y la estabilidad de coeficientes.</li>
<li>Escriba qué conclusión permiten esas 32 filas y qué población adicional no puede afirmarse sin un diseño de muestreo.</li>
</ol>
</section>
</section>
<section id="respuestas-seleccionadas" class="level2">
<h2 class="anchored" data-anchor-id="respuestas-seleccionadas">Respuestas seleccionadas</h2>
<p><strong>Problema 1.</strong> Los MSE de validación para grados 1, 3, 8 y 15 son aproximadamente 2.223, 2.172, 2.379 y 3.254. El mínimo de entrenamiento del grado 15 no justifica escogerlo: la configuración se elige con observaciones que no intervinieron en sus coeficientes.</p>
<p><strong>Problema 3.</strong> Si una dirección tiene <span class="math inline">\(\sigma_j\)</span> pequeño, OLS multiplica la componente correspondiente de <span class="math inline">\(\mathbf U^\top\mathbf y\)</span> por <span class="math inline">\(1/\sigma_j\)</span>. Ridge la multiplica por <span class="math inline">\(\sigma_j/(\sigma_j^2+n\lambda)\)</span>, que permanece acotado y tiende a cero cuando <span class="math inline">\(\lambda\)</span> crece.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./capitulo02_descenso_gradiente.html" class="pagination-link" aria-label="Descenso del gradiente">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Descenso del gradiente</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./capitulo04_regresion_logistica.html" class="pagination-link" aria-label="Regresión logística">
        <span class="nav-page-text"><span class="chapter-title">Regresión logística</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>