<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Descenso del gradiente – MATE-2105: Módulo 1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./capitulo03_regularizacion_validacion.html" rel="next">
<link href="./capitulo01_regresion_lineal.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-bf8030b5a8b8f2de5bceddfb8bf38a1d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./capitulo02_descenso_gradiente.html"><span class="chapter-title">Descenso del gradiente</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">MATE-2105: Módulo 1</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Módulo 1: Regresión, optimización, regularización y clasificación</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./capitulo01_regresion_lineal.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Regresión lineal y mínimos cuadrados</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./capitulo02_descenso_gradiente.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Descenso del gradiente</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./capitulo03_regularizacion_validacion.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Validación y regularización</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./capitulo04_regresion_logistica.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Regresión logística</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./capitulo05_ejercicios_integradores.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Problemas integradores de regresión y clasificación</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./apendice_formulario_respuestas.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Apéndice Módulo 1: formulario y respuestas seleccionadas</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./laboratorios/lab01_regresion_gradiente.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lab 1: Regresión lineal y descenso del gradiente</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./laboratorios/lab02_regularizacion_clasificacion.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lab 2: Regularización, validación y clasificación</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./laboratorios/parcial01_autograded.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Parcial 1 autograded</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./recursos/guia_parcial1.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Guía de preparación Parcial 1</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./recursos/guia_proyecto_modulo01.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Proyecto durante el Módulo 1</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#de-la-derivada-a-un-algoritmo" id="toc-de-la-derivada-a-un-algoritmo" class="nav-link active" data-scroll-target="#de-la-derivada-a-un-algoritmo">De la derivada a un algoritmo</a></li>
  <li><a href="#la-tasa-decide-la-trayectoria" id="toc-la-tasa-decide-la-trayectoria" class="nav-link" data-scroll-target="#la-tasa-decide-la-trayectoria">La tasa decide la trayectoria</a></li>
  <li><a href="#la-hessiana-explica-la-estabilidad" id="toc-la-hessiana-explica-la-estabilidad" class="nav-link" data-scroll-target="#la-hessiana-explica-la-estabilidad">La Hessiana explica la estabilidad</a></li>
  <li><a href="#escala-y-condicionamiento" id="toc-escala-y-condicionamiento" class="nav-link" data-scroll-target="#escala-y-condicionamiento">Escala y condicionamiento</a></li>
  <li><a href="#verificar-gradiente-y-solución" id="toc-verificar-gradiente-y-solución" class="nav-link" data-scroll-target="#verificar-gradiente-y-solución">Verificar gradiente y solución</a></li>
  <li><a href="#costo-y-gradientes-por-subconjuntos" id="toc-costo-y-gradientes-por-subconjuntos" class="nav-link" data-scroll-target="#costo-y-gradientes-por-subconjuntos">Costo y gradientes por subconjuntos</a></li>
  <li><a href="#regreso-a-los-dos-casos" id="toc-regreso-a-los-dos-casos" class="nav-link" data-scroll-target="#regreso-a-los-dos-casos">Regreso a los dos casos</a></li>
  <li><a href="#síntesis" id="toc-síntesis" class="nav-link" data-scroll-target="#síntesis">Síntesis</a></li>
  <li><a href="#problemas-integrados" id="toc-problemas-integrados" class="nav-link" data-scroll-target="#problemas-integrados">Problemas integrados</a>
  <ul class="collapse">
  <li><a href="#seis-pasos-que-pueden-calcularse-a-mano" id="toc-seis-pasos-que-pueden-calcularse-a-mano" class="nav-link" data-scroll-target="#seis-pasos-que-pueden-calcularse-a-mano">1. Seis pasos que pueden calcularse a mano</a></li>
  <li><a href="#el-mismo-dato-en-otra-unidad" id="toc-el-mismo-dato-en-otra-unidad" class="nav-link" data-scroll-target="#el-mismo-dato-en-otra-unidad">2. El mismo dato en otra unidad</a></li>
  <li><a href="#auditoría-de-una-implementación" id="toc-auditoría-de-una-implementación" class="nav-link" data-scroll-target="#auditoría-de-una-implementación">3. Auditoría de una implementación</a></li>
  <li><a href="#optimización-en-las-subzonas" id="toc-optimización-en-las-subzonas" class="nav-link" data-scroll-target="#optimización-en-las-subzonas">4. Optimización en las subzonas</a></li>
  </ul></li>
  <li><a href="#respuestas-seleccionadas" id="toc-respuestas-seleccionadas" class="nav-link" data-scroll-target="#respuestas-seleccionadas">Respuestas seleccionadas</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Descenso del gradiente</span></h1>
<p class="subtitle lead">Iteraciones, estabilidad y geometría de la optimización</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>En el capítulo anterior, <code>np.linalg.lstsq</code> calculó directamente el minimizador de</p>
<p><span class="math display">\[
\widehat R_n(\boldsymbol\theta)
=\frac1{2n}
\lVert\mathbf X\boldsymbol\theta-\mathbf y\rVert_2^2.
\]</span></p>
<p>Supongamos ahora que solo podemos evaluar su gradiente. Para tres observaciones con <span class="math inline">\(x=(-1,0,1)\)</span>, <span class="math inline">\(y=(1,3,5)\)</span> e intercepto, comenzamos en <span class="math inline">\(\boldsymbol\theta^{(0)}=(0,0)\)</span>. El gradiente inicial es</p>
<p><span class="math display">\[
\nabla\widehat R_n(\boldsymbol\theta^{(0)})
=\frac13\mathbf X^\top
(\mathbf X\boldsymbol\theta^{(0)}-\mathbf y)
=\begin{bmatrix}-3\\-4/3\end{bmatrix}.
\]</span></p>
<p>Moverse una distancia <span class="math inline">\(\alpha=0.2\)</span> en la dirección opuesta produce</p>
<p><span class="math display">\[
\boldsymbol\theta^{(1)}
=\boldsymbol\theta^{(0)}
-0.2\nabla\widehat R_n(\boldsymbol\theta^{(0)})
=\begin{bmatrix}0.6\\0.267\end{bmatrix}.
\]</span></p>
<p>La pérdida baja de 5.833 a 3.881. No hemos resuelto un sistema ni formado una inversa: usamos información local para construir una secuencia de parámetros.</p>
<section id="de-la-derivada-a-un-algoritmo" class="level2">
<h2 class="anchored" data-anchor-id="de-la-derivada-a-un-algoritmo">De la derivada a un algoritmo</h2>
<p>Para una función diferenciable <span class="math inline">\(J:\mathbb R^p\to\mathbb R\)</span>, el gradiente <span class="math inline">\(\nabla J(\boldsymbol\theta)\)</span> señala la dirección de mayor crecimiento local. La aproximación de Taylor</p>
<p><span class="math display">\[
J(\boldsymbol\theta+\boldsymbol h)
\approx J(\boldsymbol\theta)
+\nabla J(\boldsymbol\theta)^\top\boldsymbol h
\]</span></p>
<p>muestra que, entre desplazamientos de norma fija y suficientemente pequeña, la elección <span class="math inline">\(\boldsymbol h\)</span> opuesta al gradiente produce la mayor disminución de primer orden. El descenso del gradiente repite</p>
<p><span class="math display">\[
\boldsymbol\theta^{(t+1)}
=\boldsymbol\theta^{(t)}
-\alpha\nabla J(\boldsymbol\theta^{(t)}),
\]</span></p>
<p>donde <span class="math inline">\(\alpha&gt;0\)</span> es la tasa de aprendizaje.</p>
<p>Para mínimos cuadrados,</p>
<p><span class="math display">\[
\nabla\widehat R_n(\boldsymbol\theta)
=\frac1n\mathbf X^\top
(\mathbf X\boldsymbol\theta-\mathbf y).
\]</span></p>
<p>La siguiente implementación guarda la pérdida inicial y la obtenida después de cada actualización. Las firmas coinciden con las utilizadas en los notebooks del módulo.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> half_mse_loss(X, y, theta):</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    error <span class="op">=</span> X <span class="op">@</span> theta <span class="op">-</span> y</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="fl">0.5</span> <span class="op">*</span> np.mean(error <span class="op">**</span> <span class="dv">2</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> gradient_descent(X, y, alpha<span class="op">=</span><span class="fl">0.1</span>, max_iter<span class="op">=</span><span class="dv">1000</span>, tol<span class="op">=</span><span class="fl">1e-8</span>):</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    n, p <span class="op">=</span> X.shape</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    theta <span class="op">=</span> np.zeros(p, dtype<span class="op">=</span><span class="bu">float</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    history <span class="op">=</span> [half_mse_loss(X, y, theta)]</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(max_iter):</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>        gradient <span class="op">=</span> X.T <span class="op">@</span> (X <span class="op">@</span> theta <span class="op">-</span> y) <span class="op">/</span> n</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="kw">not</span> np.<span class="bu">all</span>(np.isfinite(gradient)):</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>            <span class="cf">raise</span> <span class="pp">FloatingPointError</span>(<span class="st">"gradiente no finito"</span>)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> np.linalg.norm(gradient) <span class="op">&lt;=</span> tol:</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>            <span class="cf">break</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>        theta <span class="op">=</span> theta <span class="op">-</span> alpha <span class="op">*</span> gradient</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>        loss <span class="op">=</span> half_mse_loss(X, y, theta)</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="kw">not</span> np.isfinite(loss):</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>            <span class="cf">raise</span> <span class="pp">FloatingPointError</span>(<span class="st">"pérdida no finita"</span>)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>        history.append(loss)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> theta, np.asarray(history)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>En el ejemplo inicial, las primeras iteraciones con <span class="math inline">\(\alpha=0.2\)</span> son:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">iteración</th>
<th style="text-align: right;">intercepto</th>
<th style="text-align: right;">pendiente</th>
<th style="text-align: right;">pérdida</th>
<th style="text-align: right;">norma del gradiente</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">5.833</td>
<td style="text-align: right;">3.283</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.600</td>
<td style="text-align: right;">0.267</td>
<td style="text-align: right;">3.881</td>
<td style="text-align: right;">2.664</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">1.080</td>
<td style="text-align: right;">0.498</td>
<td style="text-align: right;">2.595</td>
<td style="text-align: right;">2.165</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">1.464</td>
<td style="text-align: right;">0.698</td>
<td style="text-align: right;">1.745</td>
<td style="text-align: right;">1.764</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;">1.771</td>
<td style="text-align: right;">0.872</td>
<td style="text-align: right;">1.179</td>
<td style="text-align: right;">1.441</td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: right;">2.017</td>
<td style="text-align: right;">1.022</td>
<td style="text-align: right;">0.802</td>
<td style="text-align: right;">1.180</td>
</tr>
</tbody>
</table>
<p>El minimizador es <span class="math inline">\((3,2)\)</span>. Cada columna progresa a una velocidad distinta; la secuencia todavía no ha convergido después de cinco pasos, pero la pérdida y la norma del gradiente disminuyen de manera coherente.</p>
</section>
<section id="la-tasa-decide-la-trayectoria" class="level2">
<h2 class="anchored" data-anchor-id="la-tasa-decide-la-trayectoria">La tasa decide la trayectoria</h2>
<p>La dirección del gradiente no fija la longitud del paso. En una superficie convexa, un paso pequeño puede avanzar lentamente y uno grande puede atravesar el valle y aumentar la pérdida.</p>
<div id="fig-cap02-descenso-gradiente-trayectoria" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Mapa de contornos de una pérdida convexa con puntos sucesivos que avanzan hacia el mínimo, junto con tres escenarios de tasa de aprendizaje pequeña, razonable y grande.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cap02-descenso-gradiente-trayectoria-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figuras/descenso-gradiente-trayectoria.svg" class="img-fluid figure-img" style="width:100.0%" alt="Mapa de contornos de una pérdida convexa con puntos sucesivos que avanzan hacia el mínimo, junto con tres escenarios de tasa de aprendizaje pequeña, razonable y grande.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cap02-descenso-gradiente-trayectoria-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.1: Descenso del gradiente: la trayectoria avanza sobre contornos de pérdida y la tasa de aprendizaje controla si el avance es lento, estable u oscilatorio.
</figcaption>
</figure>
</div>
<p>Con el mismo ejemplo, <span class="math inline">\(\alpha=1.8\)</span> hace oscilar el intercepto alrededor de 3, aunque la pérdida decrece. Con <span class="math inline">\(\alpha=2.2\)</span> la pérdida comienza en 5.833 y luego toma los valores 6.770, 9.394, 13.451 y 19.352: el algoritmo diverge. Ni la convexidad de la pérdida ni la corrección del gradiente hacen estable cualquier tasa.</p>
<p>Una curva de pérdida debe leerse junto con la norma del gradiente y el estado de los parámetros:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>comportamiento</th>
<th>explicación compatible</th>
<th>comprobación siguiente</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>disminución suave</td>
<td>paso estable</td>
<td>comparar con una solución de referencia</td>
</tr>
<tr class="even">
<td>disminución muy lenta</td>
<td>paso pequeño o geometría alargada</td>
<td>revisar escala y espectro</td>
</tr>
<tr class="odd">
<td>oscilación decreciente</td>
<td>paso cercano al límite de estabilidad</td>
<td>reducir <span class="math inline">\(\alpha\)</span></td>
</tr>
<tr class="even">
<td>crecimiento sostenido</td>
<td>paso fuera del intervalo estable</td>
<td>detener y reducir <span class="math inline">\(\alpha\)</span></td>
</tr>
<tr class="odd">
<td><code>nan</code> o <code>inf</code></td>
<td>desbordamiento tras divergencia</td>
<td>revisar primero la historia finita</td>
</tr>
<tr class="even">
<td>pérdida estable pero alta</td>
<td>familia limitada o parada prematura</td>
<td>separar optimización de modelado</td>
</tr>
</tbody>
</table>
<p>Que la pérdida de entrenamiento converja solo responde si el algoritmo resolvió el problema empírico. No demuestra que la familia sea adecuada ni que el modelo funcione en observaciones nuevas.</p>
</section>
<section id="la-hessiana-explica-la-estabilidad" class="level2">
<h2 class="anchored" data-anchor-id="la-hessiana-explica-la-estabilidad">La Hessiana explica la estabilidad</h2>
<p>En mínimos cuadrados la Hessiana es constante:</p>
<p><span class="math display">\[
\mathbf H
=\nabla^2\widehat R_n(\boldsymbol\theta)
=\frac1n\mathbf X^\top\mathbf X.
\]</span></p>
<p>Supongamos primero que <span class="math inline">\(\mathbf X\)</span> tiene rango columna completo. Si <span class="math inline">\(\boldsymbol\theta^*\)</span> es el minimizador y <span class="math inline">\(\boldsymbol e_t=\boldsymbol\theta^{(t)}-\boldsymbol\theta^*\)</span>, entonces</p>
<p><span class="math display">\[
\begin{aligned}
\boldsymbol e_{t+1}
&amp;=\boldsymbol e_t-\alpha\mathbf H\boldsymbol e_t\\
&amp;=(\mathbf I-\alpha\mathbf H)\boldsymbol e_t.
\end{aligned}
\]</span></p>
<p>Sea <span class="math inline">\(\mathbf H=\mathbf Q\boldsymbol\Lambda\mathbf Q^\top\)</span> y denote sus valores propios por <span class="math inline">\(0&lt;\lambda_1\leq\cdots\leq\lambda_p\)</span>. La componente del error en la dirección propia <span class="math inline">\(j\)</span> se multiplica por <span class="math inline">\(1-\alpha\lambda_j\)</span> en cada iteración. Todas las componentes se contraen exactamente cuando</p>
<p><span class="math display">\[
|1-\alpha\lambda_j|&lt;1
\quad\text{para todo }j,
\]</span></p>
<p>o, de manera equivalente,</p>
<p><span class="math display">\[
0&lt;\alpha&lt;\frac{2}{\lambda_{\max}(\mathbf H)}.
\]</span></p>
<div class="proposicion">
<p><strong>Convergencia en la pérdida cuadrática.</strong> Si <span class="math inline">\(\mathbf X\)</span> tiene rango columna completo y <span class="math inline">\(0&lt;\alpha&lt;2/\lambda_{\max}(\mathbf H)\)</span>, el descenso del gradiente con paso constante converge linealmente al único minimizador. Si <span class="math inline">\(\mathbf H\)</span> es singular, las componentes iniciales en su espacio nulo no cambian y el vector de parámetros límite puede no ser único.</p>
</div>
<p>La tasa que equilibra las dos direcciones extremas de una cuadrática definida positiva es</p>
<p><span class="math display">\[
\alpha_{\mathrm{opt}}
=\frac{2}{\lambda_{\min}(\mathbf H)+\lambda_{\max}(\mathbf H)},
\]</span></p>
<p>con factor de contracción máximo</p>
<p><span class="math display">\[
\rho
=\frac{\kappa_2(\mathbf H)-1}{\kappa_2(\mathbf H)+1}.
\]</span></p>
<p>La fórmula explica el fenómeno, pero no es una receta general. Calcular el espectro completo puede costar tanto como resolver el problema y, fuera de una cuadrática, la Hessiana cambia con los parámetros.</p>
</section>
<section id="escala-y-condicionamiento" class="level2">
<h2 class="anchored" data-anchor-id="escala-y-condicionamiento">Escala y condicionamiento</h2>
<p>Una misma variable expresada en unidades distintas contiene la misma información, pero produce una geometría numérica diferente. Multipliquemos <code>x2</code> del conjunto sintético por 1000. El diseño resultante tiene aproximadamente</p>
<p><span class="math display">\[
\kappa_2(\mathbf X)=1311,
\qquad
\lambda_{\max}(\mathbf H)=1.189\times10^6.
\]</span></p>
<p>La condición teórica de estabilidad exige entonces</p>
<p><span class="math display">\[
\alpha&lt;1.68\times10^{-6}.
\]</span></p>
<p>Después de centrar cada característica y dividirla por su desviación estándar, sin transformar la columna de intercepto, se obtiene</p>
<p><span class="math display">\[
\kappa_2(\mathbf X_{\mathrm{esc}})=2.16,
\qquad
\lambda_{\max}(\mathbf H_{\mathrm{esc}})=1.657,
\]</span></p>
<p>y el límite aumenta a aproximadamente 1.207. No apareció información nueva; se modificaron las coordenadas en las que el algoritmo recorre la pérdida.</p>
<p>La estandarización de una característica <span class="math inline">\(j\)</span> utiliza</p>
<p><span class="math display">\[
z_{ij}=\frac{x_{ij}-\mu_j}{s_j}.
\]</span></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>mu <span class="op">=</span> X_features.mean(axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>scale <span class="op">=</span> X_features.std(axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>scale[scale <span class="op">==</span> <span class="dv">0</span>] <span class="op">=</span> <span class="fl">1.0</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>Z <span class="op">=</span> (X_features <span class="op">-</span> mu) <span class="op">/</span> scale</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>X_scaled <span class="op">=</span> add_intercept(Z)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Cuando se evalúe fuera de la muestra de ajuste, <span class="math inline">\(\mu_j\)</span> y <span class="math inline">\(s_j\)</span> deberán calcularse solo con entrenamiento y reutilizarse sin volverlos a estimar. El capítulo siguiente formalizará esta restricción al introducir particiones y filtración de información.</p>
<div class="diagnostico">
<p><strong>Escalar no corrige colinealidad.</strong> La estandarización puede equilibrar unidades, pero dos columnas casi redundantes continúan casi redundantes. Si un valor singular permanece cercano a cero después de escalar, el problema requiere revisar el diseño o introducir regularización.</p>
</div>
</section>
<section id="verificar-gradiente-y-solución" class="level2">
<h2 class="anchored" data-anchor-id="verificar-gradiente-y-solución">Verificar gradiente y solución</h2>
<p>Una implementación del gradiente debe comprobarse antes de interpretar su curva. La diferencia central en la coordenada <span class="math inline">\(j\)</span> es</p>
<p><span class="math display">\[
g_j^{\mathrm{num}}
=\frac{J(\boldsymbol\theta+h\boldsymbol e_j)
-J(\boldsymbol\theta-h\boldsymbol e_j)}{2h}.
\]</span></p>
<p>Para un <span class="math inline">\(h\)</span> moderadamente pequeño, el vector numérico debe aproximar el gradiente analítico:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> finite_difference_gradient(loss, theta, h<span class="op">=</span><span class="fl">1e-6</span>):</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    gradient <span class="op">=</span> np.empty_like(theta, dtype<span class="op">=</span><span class="bu">float</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(theta.size):</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>        direction <span class="op">=</span> np.zeros_like(theta, dtype<span class="op">=</span><span class="bu">float</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>        direction[j] <span class="op">=</span> h</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>        gradient[j] <span class="op">=</span> (</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>            loss(theta <span class="op">+</span> direction) <span class="op">-</span> loss(theta <span class="op">-</span> direction)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>        ) <span class="op">/</span> (<span class="dv">2</span> <span class="op">*</span> h)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> gradient</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>theta0 <span class="op">=</span> np.zeros(X.shape[<span class="dv">1</span>])</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>analytic <span class="op">=</span> X.T <span class="op">@</span> (X <span class="op">@</span> theta0 <span class="op">-</span> y) <span class="op">/</span> X.shape[<span class="dv">0</span>]</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>numeric <span class="op">=</span> finite_difference_gradient(</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>    <span class="kw">lambda</span> theta: half_mse_loss(X, y, theta), theta0</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> np.allclose(analytic, numeric, rtol<span class="op">=</span><span class="fl">1e-5</span>, atol<span class="op">=</span><span class="fl">1e-7</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Después se compara el límite del algoritmo con <code>lstsq</code> usando exactamente la misma matriz:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>theta_ref <span class="op">=</span> np.linalg.lstsq(X_scaled, y, rcond<span class="op">=</span><span class="va">None</span>)[<span class="dv">0</span>]</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>theta_gd, history <span class="op">=</span> gradient_descent(</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    X_scaled, y, alpha<span class="op">=</span><span class="fl">0.5</span>, max_iter<span class="op">=</span><span class="dv">10_000</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>parameter_gap <span class="op">=</span> np.linalg.norm(theta_gd <span class="op">-</span> theta_ref)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>gradient_norm <span class="op">=</span> np.linalg.norm(</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    X_scaled.T <span class="op">@</span> (X_scaled <span class="op">@</span> theta_gd <span class="op">-</span> y) <span class="op">/</span> X_scaled.shape[<span class="dv">0</span>]</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Una diferencia grande puede deberse a una tasa inestable, pocas iteraciones, un criterio de parada mal definido o un gradiente incorrecto. Comparar solo las pérdidas puede ocultar diferencias entre parámetros cuando el diseño tiene rango deficiente.</p>
</section>
<section id="costo-y-gradientes-por-subconjuntos" class="level2">
<h2 class="anchored" data-anchor-id="costo-y-gradientes-por-subconjuntos">Costo y gradientes por subconjuntos</h2>
<p>Calcular <span class="math inline">\(\mathbf X\boldsymbol\theta\)</span> y después multiplicar el error por <span class="math inline">\(\mathbf X^\top\)</span> cuesta <span class="math inline">\(O(np)\)</span> por iteración batch. Tras <span class="math inline">\(T\)</span> iteraciones, el costo es <span class="math inline">\(O(Tnp)\)</span>, además de almacenar el diseño. Una factorización directa paga aproximadamente <span class="math inline">\(O(np^2)\)</span> una vez. El método conveniente depende de <span class="math inline">\(n\)</span>, <span class="math inline">\(p\)</span>, la estructura dispersa y el número de iteraciones necesario.</p>
<p>Para un subconjunto <span class="math inline">\(B\)</span> de observaciones definimos</p>
<p><span class="math display">\[
\boldsymbol g_B(\boldsymbol\theta)
=\frac1{|B|}\sum_{i\in B}
\nabla_{\boldsymbol\theta}\ell_i(\boldsymbol\theta).
\]</span></p>
<p>Si las posiciones se seleccionan uniformemente, condicionado en el conjunto de datos,</p>
<p><span class="math display">\[
\mathbb E_B[\boldsymbol g_B(\boldsymbol\theta)]
=\nabla\widehat R_n(\boldsymbol\theta).
\]</span></p>
<p>Por tanto, el gradiente de mini-batch es un estimador condicionalmente insesgado del gradiente empírico completo. Su aleatoriedad proviene de escoger el subconjunto <span class="math inline">\(B\)</span>, una vez fijados los datos; no debe confundirse con la variación que produciría observar otra muestra de la población. Un mini-batch reduce el costo de cada paso e introduce variación entre pasos. Esta observación prepara el uso de optimizadores estocásticos en redes neuronales; en este módulo, el algoritmo de referencia seguirá utilizando todo el conjunto.</p>
</section>
<section id="regreso-a-los-dos-casos" class="level2">
<h2 class="anchored" data-anchor-id="regreso-a-los-dos-casos">Regreso a los dos casos</h2>
<p>En la población sintética, el diseño con intercepto y tres características tiene número de condición 2.17. El descenso con datos sin reescalar ya es manejable y debe converger al mismo ajuste que <code>lstsq</code>. Multiplicar <code>x2</code> por 1000 no cambia las predicciones que puede representar el modelo, pero obliga a reducir drásticamente la tasa si no se estandariza.</p>
<p>En las subzonas de Bogotá, el diseño sin escalar tiene número de condición cercano a 1237. Parte del valor se debe a que <code>area_promedio</code> vive en una escala muy distinta de los demás promedios. Estandarizar facilita la optimización y la comparación numérica de columnas, pero no corrige la agregación por subzona, la unidad desconocida de <code>precio_reportado</code> ni la dependencia entre variables. Un algoritmo puede converger con precisión a un modelo cuya interpretación siga siendo limitada.</p>
</section>
<section id="síntesis" class="level2">
<h2 class="anchored" data-anchor-id="síntesis">Síntesis</h2>
<p>El descenso del gradiente convierte una derivada en una sucesión de parámetros. La pérdida, la norma del gradiente y la comparación con una solución de referencia permiten distinguir convergencia, oscilación, divergencia y errores de implementación.</p>
<p>En una pérdida cuadrática, los valores propios de <span class="math inline">\(\mathbf X^\top\mathbf X/n\)</span> determinan el intervalo estable de tasas y la velocidad relativa de las direcciones. El escalamiento puede transformar una geometría muy alargada en otra más equilibrada sin cambiar la información del problema. No elimina colinealidad ni sustituye la evaluación estadística.</p>
<p>El próximo capítulo mostrará un conflicto diferente: una familia más flexible puede reducir la pérdida de entrenamiento y empeorar el comportamiento fuera de muestra. Allí la optimización será una parte del procedimiento, no el criterio para escoger por sí sola el modelo final.</p>
</section>
<section id="problemas-integrados" class="level2">
<h2 class="anchored" data-anchor-id="problemas-integrados">Problemas integrados</h2>
<section id="seis-pasos-que-pueden-calcularse-a-mano" class="level3">
<h3 class="anchored" data-anchor-id="seis-pasos-que-pueden-calcularse-a-mano">1. Seis pasos que pueden calcularse a mano</h3>
<p>Use <span class="math inline">\(x=(-1,0,1)\)</span>, <span class="math inline">\(y=(1,3,5)\)</span> y <span class="math inline">\(\boldsymbol\theta^{(0)}=(0,0)\)</span>.</p>
<ol type="1">
<li>Derive el gradiente y la Hessiana.</li>
<li>Calcule seis iteraciones con <span class="math inline">\(\alpha=0.2\)</span>.</li>
<li>Repita con <span class="math inline">\(\alpha=1.8\)</span> y <span class="math inline">\(\alpha=2.2\)</span>; compare las pérdidas.</li>
<li>Obtenga los valores propios de la Hessiana y determine el intervalo teórico de convergencia.</li>
<li>Explique cada trayectoria mediante los factores <span class="math inline">\(1-\alpha\lambda_j\)</span>.</li>
</ol>
</section>
<section id="el-mismo-dato-en-otra-unidad" class="level3">
<h3 class="anchored" data-anchor-id="el-mismo-dato-en-otra-unidad">2. El mismo dato en otra unidad</h3>
<p>Use <code>regresion_lineal_sintetica.csv</code> y multiplique <code>x2</code> por 1000.</p>
<ol type="1">
<li>Calcule número de condición, espectro de la Hessiana y tasa máxima teórica antes de escalar.</li>
<li>Ejecute gradiente con tasas <span class="math inline">\(10^{-7}\)</span>, <span class="math inline">\(10^{-5}\)</span> y <span class="math inline">\(0.1\)</span>.</li>
<li>Estandarice las características, mantenga intacto el intercepto y repita.</li>
<li>Convierta los coeficientes del modelo escalado a las unidades originales y compruebe que las predicciones coinciden.</li>
<li>Distinga qué cambió en la optimización, en el modelo representable y en la interpretación de los coeficientes.</li>
</ol>
</section>
<section id="auditoría-de-una-implementación" class="level3">
<h3 class="anchored" data-anchor-id="auditoría-de-una-implementación">3. Auditoría de una implementación</h3>
<p>Introduzca deliberadamente uno de estos errores: omitir <span class="math inline">\(1/n\)</span>, cambiar el signo del gradiente o devolver una pérdida anterior al último parámetro.</p>
<ol type="1">
<li>Diseñe una prueba por diferencias finitas que detecte el error.</li>
<li>Compare el resultado con <code>lstsq</code>.</li>
<li>Registre pérdida, norma del gradiente y distancia entre parámetros.</li>
<li>Corrija la función sin cambiar su firma pública.</li>
<li>Escriba qué prueba habría fallado aun si la pérdida final pareciera pequeña.</li>
</ol>
</section>
<section id="optimización-en-las-subzonas" class="level3">
<h3 class="anchored" data-anchor-id="optimización-en-las-subzonas">4. Optimización en las subzonas</h3>
<p>Use las cinco columnas numéricas del caso de Bogotá.</p>
<ol type="1">
<li>Compare el espectro y el número de condición antes y después de estandarizar.</li>
<li>Encuentre una tasa estable para cada representación sin seleccionar una semilla por su resultado.</li>
<li>Compare las predicciones de gradiente y <code>lstsq</code>.</li>
<li>Grafique la historia de pérdida con ejes y escala claramente identificados.</li>
<li>Redacte un diagnóstico que separe convergencia numérica, ajuste en las 32 filas y alcance sustantivo del dataset.</li>
</ol>
</section>
</section>
<section id="respuestas-seleccionadas" class="level2">
<h2 class="anchored" data-anchor-id="respuestas-seleccionadas">Respuestas seleccionadas</h2>
<p><strong>Problema 1.</strong> La Hessiana es</p>
<p><span class="math display">\[
\mathbf H=
\begin{bmatrix}1&amp;0\\0&amp;2/3\end{bmatrix},
\]</span></p>
<p>por lo que el intervalo estable es <span class="math inline">\(0&lt;\alpha&lt;2\)</span>. Con <span class="math inline">\(\alpha=2.2\)</span>, la componente asociada a <span class="math inline">\(\lambda=1\)</span> se multiplica por <span class="math inline">\(-1.2\)</span> y crece en magnitud; la divergencia no se debe a un mínimo local.</p>
<p><strong>Problema 2.</strong> Antes de escalar, <span class="math inline">\(\kappa_2(\mathbf X)\approx1311\)</span> y <span class="math inline">\(\alpha_{\max}\approx1.68\times10^{-6}\)</span>. Después de escalar, <span class="math inline">\(\kappa_2(\mathbf X)\approx2.16\)</span> y <span class="math inline">\(\alpha_{\max}\approx1.207\)</span>. Las dos parametrizaciones pueden producir las mismas predicciones lineales; sus recorridos numéricos no son iguales.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./capitulo01_regresion_lineal.html" class="pagination-link" aria-label="Regresión lineal y mínimos cuadrados">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Regresión lineal y mínimos cuadrados</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./capitulo03_regularizacion_validacion.html" class="pagination-link" aria-label="Validación y regularización">
        <span class="nav-page-text"><span class="chapter-title">Validación y regularización</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>